---
routes:

    #########################################################
    # contacts / NODES                                          #
    #########################################################

    be_contacts:
        service:    contacts
        path:       /api/contacts
        pattern:    /api/contacts
        label:      contacts
        dscr:       A routegroup, no methods here.

    #########################################################
    # contacts / HEALTH                                         #
    #########################################################

    be_contacts_health_v1:
        pattern:    ${routes.be_contacts.path}/health/v1
        path:       ${routes.be_contacts.path}/health/v1
        label:      contacts health
        dscr:       A healthcheck endpoint for the microservice.
        service:    contacts
        provides:   health
        methods:
            get:    Glued\Controllers\ServiceController:health

  #########################################################
  # contacts / persons                                    #
  #########################################################

    be_contacts_v1:
      pattern:    ${routes.be_contacts.path}/v1
      path:       ${routes.be_contacts.path}/v1
      label:      Contacts
      dscr:       Address book.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:contacts_r1
        post:   Glued\Controllers\ServiceController:contacts_cu1
        put:    Glued\Controllers\ServiceController:contacts_cu1
        patch:  Glued\Controllers\ServiceController:contacts_cu1
        delete: Glued\Controllers\ServiceController:contacts_d1

    be_contacts_rels_v1:
      pattern:    ${routes.be_contacts.path}/rels/v1
      path:       ${routes.be_contacts.path}/rels/v1
      label:      Relationships
      dscr:       Relationships between persons.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:rels_r1

    be_contacts_regs_v1:
      pattern:    ${routes.be_contacts.path}/regs/v1
      path:       ${routes.be_contacts.path}/regs/v1
      label:      Registers
      dscr:       Fetching data from registers.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:regs_r1
