---
routes:

    #########################################################
    # contacts / NODES                                          #
    #########################################################

    be_contacts:
        service:    contacts
        path:       /api/contacts
        pattern:    /api/contacts
        label:      contacts
        dscr:       A routegroup, no methods here.

    #########################################################
    # contacts / HEALTH                                         #
    #########################################################

    be_contacts_health_v1:
        pattern:    ${routes.be_contacts.path}/v1/health
        path:       ${routes.be_contacts.path}/v1/health
        label:      contacts health
        dscr:       A healthcheck endpoint for the microservice.
        service:    contacts
        provides:   health
        methods:
            get:    Glued\Controllers\ServiceController:health

  #########################################################
  # contacts / persons                                    #
  #########################################################

    be_contacts_v1:
      pattern:    ${routes.be_contacts.path}/v1/objects[/{uuid}]
      path:       ${routes.be_contacts.path}/v1/objects
      label:      Contacts
      dscr:       Address book.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:contacts_r1
        post:   Glued\Controllers\ServiceController:contacts_p1

    be_contacts_refs_v1:
      pattern:    ${routes.be_contacts.path}/v1/{uuid}/refs
      path:       ${routes.be_contacts.path}/v1/refs
      label:      References
      dscr:       Relationship references between contact objects.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:refs_r1

    be_contacts_import_v1:
      pattern:    ${routes.be_contacts.path}/v1/import/{act}/{key}
      path:       ${routes.be_contacts.path}/v1/import
      label:      Import
      dscr:       Address book.
      service:    contacts
      methods:
        get:    Glued\Controllers\ServiceController:import_r1
